apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Hevon Gordon
  email: hevongordon.util@gmail.com
spec:
  memberOf: [admin]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
spec:
  type: team
  children: []