apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: hevon
spec:
  profile:
    displayName: Hevon Gordon
    email: hevongordon.util@gmail.com
  memberOf: [admin]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
spec:
  type: team
  children: []